# Generated by Django 4.1.7 on 2023-03-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('brl_rate', models.DecimalField(decimal_places=6, max_digits=30)),
                ('eur_rate', models.DecimalField(decimal_places=6, max_digits=30)),
                ('jpy_rate', models.DecimalField(decimal_places=6, max_digits=30)),
                ('rate_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
