# Generated by Django 4.1.7 on 2023-03-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='brl_rate',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='eur_rate',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='jpy_rate',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
